### ISSUE TITLE
Half precision is ignored

### ISSUE THREAD

**Issue by chschroeder** [LSX-UniWue/SuperGLEBer#3]
Hi,

I am trying to evaluate a model that uses Flash Attention 2, which requires half-precision data types (fp16 or bf16).

The respective (Hugging Face) model config specifies bfloat16, so the model should be loaded half precision by default. Additionally, I have set `model_args.torch_dtype=bfloat16` in the respective SuperGLEBer config.

Unfortunately, I always end up with `RuntimeError: FlashAttention only support fp16 and bf16 data type`, regardless of what I've tried. I have only tried the `news_class` task with this model so far, so the problem might not affect all trainers.

<details>
<summary><b>Logs:</b>  Full stack trace below</summary>

```
Error executing job with overrides: ['+model=mymodel_checkpoint1', '+task=news_class', '+train_args=a100', 'train_args.disable_qlora=True']
Traceback (most recent call last):
  File "/home/cschroeder/.pyenv/versions/3.9.18/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
  File "/path/to/my/workspace/SuperGLEBer/src/train.py", line 95, in training
    patched_train(cfg)
  File "/path/to/my/workspace/SuperGLEBer/src/train.py", line 30, in patched_train
    inner_train(cfg)
  File "/path/to/my/workspace/SuperGLEBer/src/train.py", line 85, in inner_train
    train_flair(cfg)
  File "/path/to/my/workspace/SuperGLEBer/src/train_flair.py", line 113, in training
    train_results = trainer.fine_tune(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/trainers/trainer.py", line 985, in fine_tune
    return self.train(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/trainers/trainer.py", line 549, in train
    loss, datapoint_count = self.model.forward_loss(batch_step)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/nn/model.py", line 741, in forward_loss
    data_point_tensor = self._encode_data_points(sentences, data_points)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/nn/model.py", line 712, in _encode_data_points
    data_point_tensor = torch.stack([self._get_embedding_for_data_point(data_point) for data_point in data_points])
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/nn/model.py", line 712, in <listcomp>
    data_point_tensor = torch.stack([self._get_embedding_for_data_point(data_point) for data_point in data_points])
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/models/pairwise_classification_model.py", line 88, in _get_embedding_for_data_point
    self.embeddings.embed(concatenated_sentence)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/embeddings/base.py", line 49, in embed
    self._add_embeddings_internal(data_points)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/embeddings/transformer.py", line 662, in _add_embeddings_internal
    embeddings = self._forward_tensors(tensors)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/embeddings/transformer.py", line 1319, in _forward_tensors
    return self.forward(**tensors)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/embeddings/transformer.py", line 1223, in forward
    hidden_states = self.model(input_ids, **model_kwargs)[-1]
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/my/workspace/SuperGLEBer/src/mymodel_model/modeling_mymodel.py", line 622, in forward
    layer_outputs = decoder_layer(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/my/workspace/SuperGLEBer/src/mymodel_model/modeling_mymodel.py", line 350, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/path/to/my/workspace/SuperGLEBer/src/mymodel_model/modeling_mymodel.py", line 272, in forward
    attn_output = _flash_attention_forward(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/transformers/modeling_flash_attention_utils.py", line 313, in _flash_attention_forward
    attn_output = flash_attn_func(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 880, in flash_attn_func
    return FlashAttnFunc.apply(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 546, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_forward(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 52, in _flash_attn_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.fwd(
RuntimeError: FlashAttention only support fp16 and bf16 data type
```

</details>

----

Edit:
Interestingly, the provided `model/leo_hessian_7b.yaml` example works. I have not verified this, but I guess the automatic casting during qlora quantization hides the reported problem.

**Comment by janpf** [comment]
Hey,

thank you for your issue, we will try to replicate it.

FYI: We updated SuperGLEBer to a new version with a nicer implementation. You still seem to use the old one (which uses `train_args.disable_qlora`).

**Comment by chschroeder** [comment]
Awesome! Thank you for the quick fix, and also for the advice on using the more recent version.

**Comment by chschroeder** [comment]
With the new version

```
python src/train.py +model=+model=leo_mistral_hessian_7b +train_args=a100
```

results in:

```
hydra.errors.ConfigCompositionException: train_args appears more than once in the final defaults list
```

**Comment by janpf** [comment]
> With the new version
> 
> ```
> python src/train.py +model=+model=leo_mistral_hessian_7b +train_args=a100
> ```
> 
> results in:
> 
> ```
> hydra.errors.ConfigCompositionException: train_args appears more than once in the final defaults list
> ```

yes, because `train_args=a100` is now the default (https://github.com/LSX-UniWue/SuperGLEBer/blob/7d17b75da7a1f9559965f090c135d21c260133bc/src/conf/config.yaml#L2). if you want to overwrite it you have to remove the `+` i believe :)

**Comment by chschroeder** [comment]
Oh, I see, thanks.

When specifying a task (news_class) in addition to this, I get a little further, but arrive at the next error:
```
<...>
File "/path/to/SuperGLEBer/src/train_flair.py", line 48, in train
<...>
TypeError: prepare_model_for_kbit_training() got an unexpected keyword argument 'gradient_checkpointing_kwargs'
```
From a quick glance, at least in `train_flair.py`, I will not be able to circumvent that with the config.

With a small GPT-2 model, I could successfully execute this benchmark in the past, but here now it seems a little bit more difficult.

**Comment by janpf** [comment]
huh, that's super weird. we run the code multiple times a day 🤔
could you please post the entire stack trace, CLI args and the configs you have changed, if any?

**Comment by chschroeder** [comment]
Sure. The exact command was: `python src/train.py +model=leo_hessian_7b +task=news_class`. Nothing should be changed in those configs.

<details>
<summary><b>Logs:</b>  Full stack trace below</summary>

```
Traceback (most recent call last):
  File "/home/cschroeder/workspaces/llm/SuperGLEBer2/src/train.py", line 54, in <module>
    training()
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/cschroeder/workspaces/llm/SuperGLEBer2/src/train.py", line 41, in training
    train_flair(cfg)
  File "/home/cschroeder/workspaces/llm/SuperGLEBer2/src/train_flair.py", line 101, in training
    embeddings=globals()[cfg.task.embedding_type](
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/embeddings/document.py", line 49, in __init__
    TransformerEmbeddings.__init__(
  File "/home/cschroeder/.pyenv/versions/supergleber/lib/python3.9/site-packages/flair/embeddings/transformer.py", line 1124, in __init__
    transformer_model = prepare_model_for_kbit_training(
TypeError: prepare_model_for_kbit_training() got an unexpected keyword argument 'gradient_checkpointing_kwargs'
```

</details>

This is likely a dependency problem. I set up a new venv, now I can run this config again :). Needs no further investigation from my side unless you want to pinpoint the exact dependency versions. Thanks for the help!

**Comment by janpf** [comment]
ok, nice!
FYI, we actually provide the exact dependencies used in the [requirements.txt](https://github.com/LSX-UniWue/SuperGLEBer/blob/main/requirements.txt), and also provide an already built docker image https://github.com/LSX-UniWue/SuperGLEBer/pkgs/container/supergleber

**Comment by chschroeder** [comment]
Sorry, forgot to respond since I read it late in the evening :). I use the requirements.txt of course, but I had not spotted the docker image. Thanks!
